### ISSUE TITLE
Incompatible with ES6 target

### ISSUE THREAD

**Issue by JStumpp** [thiagobustamante/typescript-rest#10]
This does not seem to be related to #4.

The Basic example fails calling the route with the error:
TypeError: Class constructor HelloService cannot be invoked without 'new'

Target: ES6
Node: v6.9.5

Workaround: Switch to ES5 and include the @types/es6-promise.

**Comment by Clowning** [comment]
Yes i've the same issue ! Can you do something about that ? Beh i want to use ES6 syntax ! Thanks :) !

**Comment by thiagobustamante** [comment]
This is in progress, and only have a general idea that I'll complete in the next few days.

**Comment by Clowning** [comment]
@thiagobustamante  Thanks! You rock dude

**Comment by thiagobustamante** [comment]
Plz, try update to 0.3.9 version
