### ISSUE TITLE
POST object with a property of Date type

### ISSUE THREAD

**Issue by lexluthor91** [thiagobustamante/typescript-rest#11]
Hello, first off, great library!

One issue I am having is, when I POST an object of a certain type, the properties of type "Date" are not deserialized into a Date object, they remain a string.

Example:

`@POST`
`postInputDataSet( @PathParam("jobId") jobId: number, paramSet: InputDataSetEntity):Promise<InputDataSetEntity> `
`{`
`        console.log(paramSet.beginDate.getDate());`
`}`

this code fails because beginDate is not a Date, but String. Would automatic deserialization of a Date be possible through this library?

**Comment by thiagobustamante** [comment]
Hi,

Thanks for your feedback.
Date should be supported. I will investigate what is happening.

**Comment by thiagobustamante** [comment]
Dates are not supported. The problem is that JSON.parse() does not handle dates automatically. 

However, it is possible to use a [reviver](https://msdn.microsoft.com/pt-br/library/cc836466(v=vs.94).aspx) to handle it.  

We can add this support to the next release.
