### ISSUE TITLE
Can you intercept the value from the PathParam decorator?

### ISSUE THREAD

**Issue by Vizzr** [thiagobustamante/typescript-rest#119]
Hi,

In my API I have specific calls with :id in the URL.
I use the @PathParam decorator to retrieve those values from the URL.
These IDs are encrypted, so I would like to have another (or replacement) decorator to automatically decrypt this value.

Is it possible to implement something like this?
I looked into it, but it seems like the @PathParam decorator is handled internally...

Thanks.

**Comment by tmilar** [comment]
Hey @Vizzr , you can access the value in the express Request object using the @PreProcessor annotation. For example

```typescript
@GET
@Path("/:id")
@PreProcessor((request: Request) => { console.log("the requested 'id' is:", request.params.id) }
public get(@PathParam("id") id: string) {
  return `accessing object ${id}`
}
```
