### ISSUE TITLE
Is it possible to instantiate services directly?

### ISSUE THREAD

**Issue by iursinoliveperson** [thiagobustamante/typescript-rest#121]
I'm trying to figure out if it's possible to pass in an instance of the service class with its dependencies injected manually rather than zero arg constructing all dependencies based on registering their class.

If this library is opinionated in favor of IOC based DI and doesn't support intantiation of classes then no big deal, but I probably won't be using it.

Thanks!

**Comment by thiagobustamante** [comment]
Yes, it is possible.

You can use the method ```Server.registerServiceFactory()``` and pass your on factory to instantiate the services. For example:

```typescript
class MyServiceFactory extends DefaultServiceFactory {
    public create(serviceClass: any) {
        return new serviceClass(); // or do wherever you want to create your services, including require external modules
    }
}

Server.registerServiceFactory(new MyServiceFactory());
```

**Comment by ljwagerfield** [comment]
Your example instantiates all services using their default constructor.

What if you have two services `class Foo { ctor(x, y, z) }` and `class Bar { ctor(a, b) }`?

Please can you provide an example demonstrating how you would provide manually-constructed instances of these services?
