### ISSUE TITLE
docs: Upgrade instructions for 2.X -> 3.X missing

### ISSUE THREAD

**Issue by niklas-dahl** [thiagobustamante/typescript-rest#140]
Hey, I looked at your upgrade instruction docs https://github.com/thiagobustamante/typescript-rest/wiki/Previous-Versions#upgrade-instructions but there are sadly no instructions for going 2.X -> 3.X.

It does not seem to be a very easy update since `Server.useIoC();` was removed (and probably much more?).
The boilerplate project https://github.com/vrudikov/typescript-rest-boilerplate is at 2.X also.

A guide would be much appreciated.
Thanks for your work and this package :)

**Comment by thiagobustamante** [comment]
Thanks for pointing this. I updated the documentation and soon will upgrade the boilerplate project
