### ISSUE TITLE
Making it work with 'async-listener'

### ISSUE THREAD

**Issue by bleshik** [thiagobustamante/typescript-rest#20]
Hey,
I'm using this https://github.com/othiym23/node-continuation-local-storage as a replacement for deprecated nodejs domain package for passing request context through all callbacks and promises.
In turn, this lib uses 'async-listener', which performs some instrumentation on global.Promise:
https://github.com/othiym23/async-listener/blob/master/index.js#L457
which is a problem, because of the way typescript-rest checks response:
https://github.com/thiagobustamante/typescript-rest/blob/master/src/server-container.ts#L343

I can send you a PR fixing this particular problem by adding "wrappedPromise" to the check, but I feel like there should be a better way of fixing this. Let me know if you want me to create the PR anyway.

**Comment by thiagobustamante** [comment]
Hello, 
Yes, the code used to check if a value is a Promise is wrong, but I agree that adding 'wrappedPromise' to the check is not the best solution.

I guess that we could just check if the value has a ```then```  function declared and, in that case, use:

```typescript
Promise.resolve(valueOrPromiseItDoesntMatter).then(value => {
  //...
});
```

The promise [specification](http://www.ecma-international.org/ecma-262/6.0/#sec-promise.resolve) states that it will work if the value is a promise or not.

**Comment by thiagobustamante** [comment]
Can you confirm if this change fixes the problem to you? I tested here and it works fine for all my tests.

**Comment by bleshik** [comment]
That was fast! Yes, this fixes my issue. Thanks!
