### ISSUE TITLE
Bootstrap project

### ISSUE THREAD

**Issue by vrudikov** [thiagobustamante/typescript-rest#21]
Hi! Awesome project. Thank you very much for your work

I tried to find boilerplate, but didn't find any. So i made it by myself
But i need help to stabilize and standardize this boilerplate project
[typescript-rest-boilerplate](https://github.com/vrudikov/typescript-rest-boilerplate)

So for now i have some questions:
1) in ApiServer class i have some [initialization code](https://github.com/vrudikov/typescript-rest-boilerplate/blob/master/src/server.ts#L14) for controllers(handlers). But it's very annoying to add new class reference here each time i add new controller class

How can i avoid that and write like "hey take all classes from 'controller' folder and use them as handlers"?
Maybe you have some configuration var or class for such type of behavior?

2) What files i missed? Maybe tslint.json, .editorconfig, etc.

More questions coming soon....

**Comment by thiagobustamante** [comment]
Hi, 

Thanks for it! I created a [pull request](https://github.com/vrudikov/typescript-rest-boilerplate/pull/1) to include some things, like lint / docs and tests.

Currently, the best way to include routes are described [here](https://github.com/thiagobustamante/typescript-rest/issues/9). But i like your idea to include some feature to allow us to inform a folder or some kind of expression like ```./src/controllers/*.ts``` to register routes automatically. Let's open a new issue here to include this enhancement.

**Comment by mamingzhi** [comment]
This is a great project. I like it.
Here, I have a question about service endpoint. for example,
    @Response<any>(200, 'Successful!')
    @Response<Error>(500, 'Invocation error.')
    @GET
    public sayHello(): Promise<any> {
        return new Promise<any>((resolve, reject) => {  
          const flag=false;		
          if(flag){		  
            resolve({status:"Successful"});
		  }else{
		     reject(new Error("Have a error!"))
		  }
		  
        });
    }

when flag = true, the sayHello return JSON to client (response code: 200, "content-type": "application/json; charset=utf-8")
but when flag = false the sayHello return HTML to client (response code: 500, "content-type": "text/html; charset=utf-8")

I want  sayHello return JSON when the response code = 500, how can I do it?

Thanks a lot,
Mike

**Comment by vrudikov** [comment]
@mamingzhi Hi! have you read [Official Doc for errors](https://github.com/thiagobustamante/typescript-rest#errors)

**Comment by mamingzhi** [comment]
@vrudikov , Thank you for your kind reply, I will research it.

**Comment by mamingzhi** [comment]
@vrudikov , sorry, I did not explain the entirety problem, when I used the Error.InternalServerError or other Errors. the response header is still  "content-type": "text/html; charset=utf-8" and I got a page with below html,
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
**<pre>error message is here</pre>**
</body>
</html>
```
I am researching the method "sendValue" in  server-container.ts, currently, I do not find the root cause. 
 `private sendValue(value: any, res: express.Response, next: express.NextFunction) {...}`

I know it is not an error and the typescript-rest design is reasonable. however, our project ask "application/json; charset=utf-8" for "200","400", "401", "500", "501"....

**Comment by thiagobustamante** [comment]
Hi @mamingzhi ,

Please visit the issue #16 . It talks about this problem. And feel free to comment there and make any suggestion.

**Comment by mamingzhi** [comment]
@thiagobustamante ,
Thank you so much. now I got your ideas. 
Since typescript-rest is based on ExpressJs, I agree on
`So I think that the most reasonable solution is to allow the developer to specify how he wants to sent his error.... And express already allow it through a custom error handler`.

**Comment by thiagobustamante** [comment]
Hi @vrudikov ,

I created a new issue (#24) for your request about a new way to register the services.

**Comment by vrudikov** [comment]
Hi @thiagobustamante. Thank you

**Comment by vrudikov** [comment]
@thiagobustamante Really enjoying your project. So similar to Java Spring Web Framework. Clean API. Awesome. We need to move it forward
