### ISSUE TITLE
Unable to resolve signature of method decorator when called as an expression

### ISSUE THREAD

**Issue by vellengs** [thiagobustamante/typescript-rest#25]
> Executing task: tsc -p "/Users/x x x x x/workspace/example/ts-rest/tsconfig.json" <

index.ts(7,3): error TS1241: Unable to resolve signature of method decorator when called as an expression.
The terminal process terminated with exit code: 2
--------------------------------
use code from basic example
---------------------------------
import * as express from "express";
import {Server, Path, GET, PathParam} from "typescript-rest";

@Path("/hello")
class HelloService {
  @Path(":name")
  @GET
  sayHello( @PathParam('name') name: string): string {
    return "Hello " + name;
  }
}

let app: express.Application = express();
Server.buildServices(app);

app.listen(3000, function() {
  console.log('Rest Server listening on port 3000!');
});

**Comment by vellengs** [comment]
I solved it with tsconfig.json
------------------------------
{
	"compilerOptions": {
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true,
		"module": "commonjs",
		"target": "es2016"
	},
	"include": [
		"src/**/*.ts"
	]
}

**Comment by thiagobustamante** [comment]
Yes.  

```json
"experimentalDecorators": true,
"emitDecoratorMetadata": true
```

Is required to this library work
