### ISSUE TITLE
How to use express middleware with typescript-rest

### ISSUE THREAD

**Issue by michaelkruglos** [thiagobustamante/typescript-rest#27]
I'd like to have a middleware, like authorization middleware for example.
How can I use middleware with typescript-rest.

Suppose I have something like this:
```javascript
app = express();
const myMiddleware = (req, res, next) => {
  console.log("I'm in the middle");
  next();
}

@Path("/get")
class MyGetController {
  @GET
  getSomething() {
    return "Some response";
  }
}

app.use('/api', myMiddleware, MyGetController);
```

How can I do it? How can I augment a class with some middleware in front of it?
How can I use typescript-rest to write middleware, and to compose middleware with controllers?

**Comment by thiagobustamante** [comment]
Typescript-rest receives an express router as parameter to build the routes for all controllers. You can add any middleware to this router as you do using pure express:

```typescript
app = express();
const myMiddleware = (req, res, next) => {
  console.log("I'm in the middle");
  next();
}

@Path("/get")
class MyGetController {
  @GET
  getSomething() {
    return "Some response";
  }
}
app.use(myMiddleware);
Server.buildServices(app);
```

Or using a router:

```typescript
const app = express();
const myMiddleware = (req, res, next) => {
  console.log("I'm in the middle");
  next();
}

@Path("/get")
class MyGetController {
  @GET
  getSomething() {
    return "Some response";
  }
}
const apis = express.Router();
apis.use(myMiddleware);
Server.buildServices(apis);

app.use('/apis', apis);
```
Remember that, as any other middleware for express, the order where you add your middlewares matters.

For authentication example, check [this issue](https://github.com/thiagobustamante/typescript-rest/issues/23)
