### ISSUE TITLE
How to implement filters/middleware documentation

### ISSUE THREAD

**Issue by nkimaina** [thiagobustamante/typescript-rest#30]
Could you please add some documentation on the read me file, on how one might implement some middle-ware or filters? 
A good use-case is for someone looking to implement authentication and authorization. 

Thanks

**Comment by creadicted** [comment]
Is authentication and authorization not just a route that you call that creates a response based on your model? Middleware you can just add like in express: 
https://github.com/thiagobustamante/typescript-rest#registering-services

**Comment by nkimaina** [comment]
Sorry I didn't state what I wanted to achieve clearly. I was looking for a way to do an interceptor (or transfer control to some chunk of code), before control is given to a certain route handler. 
That way, you can do checks to determine if a route can be executed or not. I am coming from a hapijs background, and we could achieve this using hapijs plugins. In microsoft's web api, they are called 'filters'.

**Comment by nkimaina** [comment]
I saw that someone asked a similar question. https://github.com/thiagobustamante/typescript-rest/issues/23. I now see how to do it. I wish it was possible to do something like:
//import some auth filter that is singleton 
import authFilter from './some-authentication-filter';

//inside a controller class
    @GET
    @Path('test')
    @Filter(authFilter)
    async test( ) {
        let result = await this.aPromiseMethod();
        return result;
    }


Looks elegant, doesn't it? Maybe this is supposed to be a feature request to implement such a decorator? I could do such a thing if you guided me.

**Comment by thiagobustamante** [comment]
Hi, 

Typescript-rest works over [expressjs](http://www.expressjs.com). Express allows you to create middlewares to intercept your requests. Take a look at [this](http://expressjs.com/en/guide/writing-middleware.html) and [this](http://expressjs.com/en/guide/using-middleware.html) to work how to create middlewares to express.

Check [this](#27) for example of using express middlewares with typescript-rest and [this] (23) for authentication.

**Comment by ngraef** [comment]
The new [`@Preprocessor` feature](https://github.com/thiagobustamante/typescript-rest#preprocessors) should solve this issue.

**Comment by nkimaina** [comment]
This is awesome! Thanks so much @ngraef
