### ISSUE TITLE
File upload with @FileParam('file') file: Express.Multer.File

### ISSUE THREAD

**Issue by creadicted** [thiagobustamante/typescript-rest#39]
I am testing the `@FileParam('file') file: Express.Multer.File` parameter. 
I initially set up the server to use multer: 

```
        const storage = multer.diskStorage({
            destination: function (req, file, cb) {
                cb(null, __dirname + '/resources/');
            },
            filename: function (req, file, cb) {
                cb(null, file.originalname + '-' + Date.now());
            }
        });

        this.app.use(multer({storage: storage, dest: __dirname + '/resources/'}).any());
```
then I use the parmeter in my controller: 

```
        public async uploadFike(@FileParam('file') file: Express.Multer.File): Promise<IFileCreation> {
       Logger.debug(file) // file is always empty
        }
```
Can I address the file variable after it was uploaded? for me `file` is empty. I am new to multer so i don't know if I am missing something...

**Comment by creadicted** [comment]
Since the file is created could it be that the service does not wait till the file is created and continues with the function?

**Comment by creadicted** [comment]
So, what I initially missed was the description of. 
```
Server.setFileDest(__dirname + '/../uploads');
```
Mentioned in the documentation. Then I got the data in the controller and could handle it with the file service. 
```
await fs.copyFileSync(file.path, __dirname + '/../../../uploads/' + path);
```

**Comment by eprokhor** [comment]
> Since the file is created could it be that the service does not wait till the file is created and continues with the function?

Did you need to do this?
