### ISSUE TITLE
Overloading of annotated inherited methods seem not to work for PUT

### ISSUE THREAD

**Issue by D054981** [thiagobustamante/typescript-rest#40]
Hi there,
I managed to create a base REST endpoint defined using your library and it worked like a charm. Now I'm inheriting from this base service and try to overload the @Get and the @Put methods for a specific endpoint that differs only in those methods.

It's working fine for the @Get case but it's complaing on the @Put where the setup is the same I guess. The error is: 

**Method is already annotated with @1. You can only map a method to one HTTP verb.**

Here a sripped down version of my classes:

abstract BaseService:
`class BaseService {
@Path(':id')
    @GET
    public getEntity(@PathParam('id') id: string, @QueryParam('$expand') expand: string): Promise<string> {
... some code
}

@Path(':id')
    @PUT
    public updateEntity(@PathParam('id') id: string, entity: any): Promise<string> {
... some code
}
}`

The class that extends the previous one:
`@Path('/admin/viewconfig')
export class ViewConfigService extends BaseService {
@Path(':id')
    @GET
    public getEntity(@PathParam('id') viewid: string): Promise<string> {
... some coding here... this overloading is working!
}

@Path(':id')
    @PUT
    public updateEntity(@PathParam('id') viewId: string, entity: any): Promise<string> {
... some code - but this overloading is complaining
}
}`

Do you have any idea why it is working for GET but not for PUT???

Thx in advance...

**Comment by thiagobustamante** [comment]
@D054981 , I created a test case here and reproduced your problem. 

It is a bug. I am working to fix it. Thanks

**Comment by thiagobustamante** [comment]
Hi @D054981,

I fixed to issue, however, take a look on this note about [abstract service classes](https://github.com/thiagobustamante/typescript-rest#inheritance-and-abstract-services) that I added to documentation.

**Comment by D054981** [comment]
Hi @thiagobustamante,
thanks a lot for the quick response and fix as well as for the good documentation.
