### ISSUE TITLE
Decorator of custom extensions?

### ISSUE THREAD

**Issue by bruegth** [thiagobustamante/typescript-rest#45]
Like:
  @Path("status")
  @Tags("status")
  @Response<string>(200 "Okay")
  @Response<string>(500, "An internal error occurs.")
  @X("custom-ext", "{ test: "test }") 
  @GET

-> x-customext: { test: "test"})

See: https://swagger.io/docs/specification/openapi-extensions/

**Comment by ttruongatl** [comment]
cool idea!
