### ISSUE TITLE
Add a Preprocessor decorator for controller class

### ISSUE THREAD

**Issue by dpkshrma** [thiagobustamante/typescript-rest#46]
It'd be really useful to have a middleware decorator that applies to all the sub-routes of a controller class like so:

```ts
@Preprocessor(logger)
@Path('/cars')
class Cars {
  ...
}
```
Here, `logger` applies to all the routes declared inside this class.

**Comment by DR-BoneZ** [comment]
#48

**Comment by thiagobustamante** [comment]
Thanks @DR-BoneZ. Available in release 1.6.0
