### ISSUE TITLE
Release new version or resolve issues with installing from GitHub

### ISSUE THREAD

**Issue by garyevari** [thiagobustamante/typescript-rest#70]
I am trying to get use of the new @Security decorator which has been merged into master, but not released on NPM. Any plans to release a new version very soon?

**Comment by garyevari** [comment]
Gave up waiting - will just maintain my own version of this package from now on.

**Comment by thiagobustamante** [comment]
@garyevari We received some pull requests with new features, like pre processors and authentication (that was not part of our original scope) and I am seeing that it is not stable enough. I am working on new tests for these features and will release soon...
