### ISSUE TITLE
Publish Library

### ISSUE THREAD

**Issue by ManuelBonjean** [thiagobustamante/typescript-rest#74]
Hi,
please publish the library on npm with passport implementation.

Thanks

**Comment by thiagobustamante** [comment]
Almost there... I am refactoring some thinks. Take a look at: [this commit](https://github.com/thiagobustamante/typescript-rest/commit/656dd893d2ef5d8d5ba17b3a5b7c78473244d273) 

I think that this will be the final version. I just need to update the documents and improve test coverage. Tomorrow I think it will be finished

**Comment by thiagobustamante** [comment]
Done! 
1.8.1 is published
