### ISSUE TITLE
Possible bug on path name and method name?

### ISSUE THREAD

**Issue by alfonsoal1983** [thiagobustamante/typescript-rest#75]
I have two services in different files:

src/controllers/v1/test.controller.ts
src/controllers/v2/test.controller.ts

The main path in the services are:

The first one

@Path('test/hello/v1')
export class TestController {
   @Path('')
   @POST
   public async testName(name: string): Promise<any> {
      console.log("hello" + name);
      return;
   }
}

The second one

@Path('test/hello/v2')
export class TestController {
   @Path('')
   @POST
   public async testName(name: string): Promise<any> {
      console.log("hello" + name);
      return;
   }
}

It throws me this error: 

node_modules\typescript-rest\dist\decorators.js:1138
throw Error('Can not use more than one body parameter on the same method.');

I've tried many options but the only way to fix it is to do this:

The first one

@Path('test/hello')
export class TestController {
   @Path('v1')
   @POST
   public async testNameV1(name: string): Promise<any> {
      console.log("hello" + name);
      return;
   }
}

The second one

@Path('test/hello')
export class TestController {
   @Path('v2')
   @POST
   public async testNameV2(name: string): Promise<any> {
      console.log("hello" + name);
      return;
   }
}

Must put the end path in the method path name and change the method name. Is it good? Another way to do something like the first option?

Thank you.

**Comment by thiagobustamante** [comment]
Yes, I could reproduce it here. It is a serious bug. Thanks for reporting it.

I am working on it
