### ISSUE TITLE
npm ignore generated folders

### ISSUE THREAD

**Issue by d0whc3r** [thiagobustamante/typescript-rest#76]
Could you add `.nyc_output`, `reports` and `node_modules` in ".npmignore"?, now when you download the package all these folders are included
Now, downloaded size is: 1.3MB
Excluding that folders size will be: ~556KB (also excluding "src" folder, size will be ~460KB)

**Comment by thiagobustamante** [comment]
Those entries are already included in .gitignore file. NPM respect the .gitignore content in addition to .npmignore.

I tested typescript-rest 2.0 with: 

```sh
mkdir new-project
cd new-project
npm init
npm i --save typescript-rest
cd node_modules/typescript-rest
ls -la
```

And I see only the expected files (no .nyc_output, reports or node_modules)

Which version are you using?

**Comment by d0whc3r** [comment]
This is from 5 month ago for version 1.8.0
Now it is solved
