### ISSUE TITLE
Inject dependencies in router

### ISSUE THREAD

**Issue by manuel-ornato** [thiagobustamante/typescript-rest#8]
Hi,
First of all, great work!
Is there a way I can inject dependencies into my router (like a repository service for instance)?
More generally can I have instance variable initialized in some way?

Manuel

**Comment by thiagobustamante** [comment]
Hi, 
Thanks for your comment. Today it is not supported, but it is a great enhancement. I will work on it to provide this implementation for the next release.

**Comment by thiagobustamante** [comment]
Hi,

Sorry about the big delay, but now it is possible. You can use [typescript-ioc](https://github.com/thiagobustamante/typescript-ioc) or even a custom serviceFactory to instantiate your service Objects.

To use typescript-ioc:

```typescript
/*Ensure to call Server.useIoC() before your service declarations. 
It only need to be called once*/
Server.useIoC();

@AutoWired
class HelloService {
  sayHello(name: string) {
    return "Hello " + name;
  }
}

@Path("/hello")
@AutoWired
class HelloRestService {
  @Inject
  private helloService: HelloService;

  @Path(":name")
  @GET
  sayHello( @PathParam('name') name: string): string {
    return this.sayHello(name);
  }
}
```  

To use a custom serviceFactory, call ```Server.registerServiceFactory``` instead of ```Server.useIoC()``` and provide your own ServiceFactory implementation.

It could be used to allow other libraries, like [Inversify](http://inversify.io/)

**Comment by manuel-ornato** [comment]
Hi Thiago,

That’s great ! Thank you.

Best regards.

Manuel

De : Thiago Bustamante [mailto:notifications@github.com]
Envoyé : mercredi 1 février 2017 02:54
À : thiagobustamante/typescript-rest
Cc : Manuel Ornato; Author
Objet : Re: [thiagobustamante/typescript-rest] Inject dependencies in router (#8)


Hi,

Sorry about the big delay, but now it is possible. You can use typescript-ioc<https://github.com/thiagobustamante/typescript-ioc> or even a custom serviceFactory to instantiate your service Objects.

To use typescript-ioc:

/*Ensure to call Server.useIoC() before your service declarations.

It only need to be called once*/

Server.useIoC();



@AutoWired

class HelloService {

  sayHello(name: string) {

    return "Hello " + name;

  }

}



@Path("/hello")

@AutoWired

class HelloRestService {

  @Inject

  private helloService: HelloService;



  @Path(":name")

  @GET

  sayHello( @PathParam('name') name: string): string {

    return this.sayHello(name);

  }

}

To use a custom serviceFactory, call Server.registerServiceFactory instead of Server.useIoC() and provide your own ServiceFactory implementation.

It could be used to allow other libraries, like Inversify<http://inversify.io/>
