### ISSUE TITLE
PostProcessor

### ISSUE THREAD

**Issue by alfonsoal1983** [thiagobustamante/typescript-rest#80]
Hello, is there any way to make an interceptor after the return to establish a global header? Just as there is the Preprocessor, the Postprocessor could also be created. Right now you can not do this unless you set said action on all calls. Neither can the express interceptor be used because the return of the function already returns the result. My problem is that I want to put an interceptor of the answer to put a header but I can not because when doing the return in the function you lose control.

**Comment by acceleratxr** [comment]
I would also like a post-processor capability.

**Comment by thiagobustamante** [comment]
Will be available in release 2.0
