### ISSUE TITLE
TypeORM Connection

### ISSUE THREAD

**Issue by alejandromorenoalberto** [thiagobustamante/typescript-rest#82]
Hello,

I'm trying to user typescript-rest with typeORM for manage my database but when I build my service, I lost the database connection. ¿How can I get connection from a service?

My app.ts looks like:

    createConnection().then(conn => {
        let app: express.Application = express();
        Server.buildServices(app, UserController);
        Server.swagger(app, './src/config/swagger.json', '/api-docs');

        app.listen(3000, function() {
            console.log('Rest Server listening on port 3000!');
        });
     });`

So after that I would call getConnection() and I get an error when I try to use it and it only happens when I built my service

Thanks you so much

**Comment by alfonsoal1983** [comment]
Hello, I have a built-in typeorm with typescript-rest and I have no problem calling the services.
I recommend you create a configuration file and another to launch the server:

AppConfig.ts
```
class AppConfig {
     public app: express.Express;
     constructor() {
          this.app = express();
          createConnection().then(conn => {
          ....
          ....    
          }
          Server.buildServices(this.app, UserController);
          Server.swagger(app, './src/config/swagger.json', '/api-docs');
    }
}
export default new AppConfig().app;
```

server.ts
```
import app from './AppConfig';
app.listen(port, host, () => {
    logger.info('Server listening on host: ' + host + ' and port: ' + port);
});
```

When you create an entity in typeorm, you do not need to call the getConnection () directly, you can call the repository from the entity itself

UserService.ts
```
class UserService {
     UserEntity.createQueryBuilder('user').getMany();
     // this is the same as
     UserEntity.find();
}
```
This should work.
