### ISSUE TITLE
I would like the ability to have optional security

### ISSUE THREAD

**Issue by acceleratxr** [thiagobustamante/typescript-rest#83]
I have endpoints that have optional security. This is useful when making a particular endpoint context sensitive such that when no auth is provided one view is returned and when auth is provided a different view is returned. When using Passport directly the optional auth endpoint would have "failWithError" set to false on the passport.authenticate options argument.

It would be great if typescript-rest support this functionality.

**Comment by thiagobustamante** [comment]
Yes, it is supported in version 2.0. Take a lookt at: https://github.com/thiagobustamante/typescript-rest/wiki/@Security-Decorator
