### ISSUE TITLE
Preprocessor Decorator should accept async code

### ISSUE THREAD

**Issue by kazzkiq** [thiagobustamante/typescript-rest#84]
As of today, Preprocessor Decorators acts as a Middlewares to endpoints.

But from my experience, if you want to prevent endpoint access from inside a Preprocessor function, you must throw an exception. This leads to issues like when you have to make an async (eg. database) operations. If your request already returned before this async call, then your Preprocessor is useless.

It would be interesting if a Preprocessor actually expected a Promise in order to know if it should trigger or not the endpoint.

A promise resolved resumes the endpoint execution, while a rejected Promise leads to an http error, for example.

c/c @DR-BoneZ

**Comment by thiagobustamante** [comment]
This is the expected behaviour. Are you facing problems with it? Which version are you using?

**Comment by thiagobustamante** [comment]
Do you have a snippet for the problem?

**Comment by kazzkiq** [comment]
Actually, it was my fault. Doing further isolated testing I noticed Promise-based Preprocessors indeed work as expected.

Closing the issue now. 🐒
