### ISSUE TITLE
Add support for IoC ContainerConfig.addSource()

### ISSUE THREAD

**Issue by mz8i** [thiagobustamante/typescript-rest#89]
When using `typescript-ioc` it is possible to register all classes in one line, like this:
```
ContainerConfig.addSource('src/**/*.js');
```
But when using `typescript-ioc` with `typescript-rest`, this configuration doesn't seem to be picked up. The only way of registering all controllers, services etc seems to be the one shown in one of the examples: creating an installers file which explicitly exports all classes you want to inject, and then passing them to `Server.buildServices()`. For large projects with lots of classes this is a bit tedious. Would it be perhaps an easy feature to implement?

**Comment by thiagobustamante** [comment]
Hi @mz8i ,

It is possible to use ```Server.loadServices```. Take a look at [this](https://github.com/thiagobustamante/typescript-rest/wiki/Server#registering-services).


Ex:
```typescript
 Server.loadServices(app, ['lib/controllers/*']); 
```
