### ISSUE TITLE
Handling incoherent HTTP responses when the result of the operation is created on a class within a npm module

### ISSUE THREAD

**Issue by alexandresouzacosta** [thiagobustamante/typescript-rest#90]
I created a npm module in typescript to reuse certain classes. However, if I throw an exception that inherits from HttpError or returns some value such as NewResource from a class of that module (which is imported inside the main module of the application), the HTTP responses are incoherent. For example, if a new resource is created using the POST verb and my class from within the module returns a NewResource, the response has status 200 (instead of 201).

**Comment by thiagobustamante** [comment]
Hi Xandão,

Can you provide me an example? I tried to reproduced but it worked as expected in my tests. Take a look at https://github.com/thiagobustamante/typescript-rest/commit/2b51bfd0b1aba7ae3f1d3cf5bdb5731540b4380f

**Comment by thiagobustamante** [comment]
Can not reproduce... Closing the issue. If you provide an example we can re-open it
