### ISSUE TITLE
Wrong Security decorator signature

### ISSUE THREAD

**Issue by Leogiciel** [thiagobustamante/typescript-rest#91]
Related to https://github.com/thiagobustamante/typescript-rest-swagger/issues/76#issue-437598884

Security decorator needs two params to be generated correctfully.

eg : 
`@Security("bearer", ["admin","operator"])`

In typescript-rest, you only implemented the second parameters (roles), so Swagger can't recognize it and generate swagger.yaml file properly : 

`            security:
                -
                    '[object Object]': []`

instead of 

`            security:
                -
                    'bearer': ["admin", "operator"]
`

**Comment by evelyne24** [comment]
I can also confirm the Auth header is broken.

**Comment by evelyne24** [comment]
This is really annoying, could you please merge the suggestion in `typescript-rest-swagger`? Otherwise, Swagger UI is unusable. Thank you!

**Comment by Leogiciel** [comment]
@evelyne24, Two fixes have been given here : https://github.com/thiagobustamante/typescript-rest-swagger/issues/76#issuecomment-495258203

**Comment by thiagobustamante** [comment]
This problem requires changes in both typescript-rest and typescript-rest-swagger projects... I finished the changes in typescript-rest and I am working to finish the changes in typescript-rest-swagger.

Typescript-rest-swagger will receive a major version soon. It is an old project that needs a refactory... And I was postponing it.


But the idea is:

Add an optional parameter to ```Server.registerAuthenticator```. It will be a second parameter to keep compatibility with the previous contract:

```typescript
Server.registerAuthenticator(new PassportAuthenticator(strategy), 'MyAuth');
```

The presious contract is still valid, and if not provided, it will register an authenticator with name ```'default'```.

It will solve the problem with swagger generation, and also allow us to define multiple authentication schemas in typescript-rest.

We can now  reference which authenticator we want to use in our classes or methods with the ```@Security``` decorator receiving an extra optional parameter.

```typescript
@Path('myPath')
export class MultipleAuthenticateRole {
    @Context
    public context: ServiceContext;

    @GET
    @Path('myPath1')
    @Security('ROLE_ADMIN', 'MyAuth')
    public test() {
        return this.context.request.user;
    }

    @GET
    @Path('myPath2')
    @Security('ROLE_ADMIN')
    public test2() {
        return this.context.request.user;
    }
}
```

In the previous example, the two endpoints will use different authenticators. The second one will use the ```'default'``` authenticator.

It is already implemented and will be available this week (I need to update the documentation before publish it to npm). But I still need to change typescript-rest-swagger. The change is to remove the decorator Security from that project and consider only the decorator defined here, in typescript-rest

**Comment by thiagobustamante** [comment]
Done. Available in 2.2.0

**Comment by Leogiciel** [comment]
Thank you. Great work, will test it tomorrow. Best regards.

**Comment by evelyne24** [comment]
I have an issue when I try to implement it as in your example:

```
node_modules/typescript-rest-swagger/dist/metadata/controllerGenerator.js:93
            scopes: d.arguments[1] ? d.arguments[1].elements.map(function (e) { return e.text; }) : undefined
                                                             ^

TypeError: Cannot read property 'map' of undefined
```
