### ISSUE TITLE
Cannot read property 'filePath' of null

### ISSUE THREAD

**Issue by alfonsoal1983** [thiagobustamante/typescript-rest#93]
Hello, when I return a null from the controller it returns this message instead of returning a null

Cannot read property 'filePath' of null

![image](https://user-images.githubusercontent.com/46220831/58268687-32a0cf00-7d86-11e9-81d7-663da13b017f.png)

The problem is in this line, it should be checked that if value is null, return that in json format

**Comment by abhisek-niyo** [comment]
I'm still getting this error.

**Comment by abhisekp** [comment]
I'm still getting this issue.
