### ISSUE TITLE
Using Error inside Preprocessor

### ISSUE THREAD

**Issue by jojokoro** [thiagobustamante/typescript-rest#94]
Hallo

I'm trying to raise friendly JSON errors if my endpoint got invalidation from [Preprocessor](https://github.com/thiagobustamante/typescript-rest/wiki/@PreProcessor-Decorator), but it won't work if I use Promises.

I tried different approaches, but **none of them actually returned my error** in JSON format (some didn't even returned the message at all)

**Example 1 (reject):**
```js
function validator(req: express.Request): Promise<any> {
  return new Promise((resolve, reject) => {
    let authToken = req.headers.authorization;

    if (!authToken) {
      return reject(new Errors.ForbiddenError("No user token provided."));
    }
  });
}
```

**Example 2 (resolve):**
```js
function validator(req: express.Request): Promise<any> {
  return new Promise((resolve) => {
    let authToken = req.headers.authorization;

    if (!authToken) {
      return resolve(new Errors.ForbiddenError("No user token provided."));
    }
  });
}
```

**Example 3 (throw):**
```js
function validator(req: express.Request): Promise<any> {
  return new Promise(() => {
    let authToken = req.headers.authorization;

    if (!authToken) {
      throw new Errors.ForbiddenError("No user token provided.");
    }
  });
}
```

The answer I would like to receive is:

```http
403 Status
Content-type: application/json
body:
{"message": "No user token provided."}
```

But instead I receive error 500 in most cases.

**Comment by thiagobustamante** [comment]
Hi @jojokoro ,

It should work for examples 1 and 3 (promise.reject and throw).

We have an working example for it in this [test case](https://github.com/thiagobustamante/typescript-rest/blob/526bc03bab69fdee9372f1bb4a7b3876452a9887/test/integration/preprocessor.spec.ts#L25).

Note that the preProcessor only raises the error. If you want to customize the body of your errors, you can create an Error Handler. Take a llok at [this](https://github.com/thiagobustamante/typescript-rest/issues/16) for more info about handling errors.
